### ISSUE TITLE
rename 'config' to options

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#26]
currently we have the top level keys. 

```yaml
config:
tasks:
watch:
```

'config' is used for task options and should be names as such to free us to use the 'config' key for actual configuration such as `cwd` etc
