### ISSUE TITLE
task-name flags (for parallel groups)

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#3]
for example, in the following case, child tasks of both `build-js` and `build-css` need to be run in series, but the two tasks themselves can run in parallel.

```yaml
tasks:
  build-all:
    - build-js
    - build-css
  build-js:
    - lint
    - webpack
    - uglify
    - manifest
  build-css:
    - sass
    - cssmin
```

we want all child tasks of `build-all` to be run in parallel, and this can be acheived on the command line by running 
```shell
$ crossbow run 'build-all@p'
```

but it's annoying having to do that so the task definition it's self should accept the flag - eg: 

```yaml
tasks:
  build-all@p:
    - build-js
    - build-css
  build-js:
    - lint
    - webpack
    - uglify
    - manifest
  build-css:
    - sass
    - cssmin
```

now this would work

```yaml
$ crossbow run build-all
```
