### ISSUE TITLE
add @bg adaptor

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#5]
Some tasks (such as watchify) need to be started effecitvely as daemons - implement `@bg` adaptor 
to allow this

**yaml**
```yaml
watch:
  # Run sass compiler
  # then run browserify in the background
  before:
    - sass
    - browserify

  # Now watch .scss files and compile sass
  watchers:
    'scss/**/*.scss': ['sass']

tasks:
  # Create the alias 'sass' for running locally installed node-sass
  sass:       '@npm node-sass --input scss/core.scss --output dist/styles.css'
  browserify: '@bg watchify app/bundle.js -d -o dist/bundle.js'

```

**json**

```json
{
    "watch": {
        "before": ["sass", "browserify"],
        "watchers": {
            "scss/**/*.scss": ["sass"]
        }
    },
    "tasks": {
        "sass": "@npm node-sass --input scss/core.scss --output dist/styles.css",
        "browserify": "@bg watchify app/bundle.js -d -o dist/bundle.js"
    }
}

```
