### ISSUE TITLE
should support --before flag for executing tasks before a watcher

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#56]

**Comment by shakyShane** [comment]
use case is where you want to share watcher definitions, but may want different start-up tasks to run before hand.

previously, you had to duplicate watcher config if you wanted different 'before' tasks

```yaml
watch:
  docker:
    before:
      - 'sass:*'
      - 'docker-up'
      - 'docker-url'
      - 'bs:init --docker'
    public/assets/scss/**:      ['sass:site:hub:builder', 'bs:inject']
    public/assets/img/**/*.svg: ['icons', 'bs:reload']
    public/**/*.php:            ['bs:reload']
    public/**/*.json:           ['bs:reload']

  default:
    before:
      - 'check-env'
      - 'sass:*'
      - 'bs:init'
    public/assets/scss/**:      ['sass:site:hub:builder', 'bs:inject']
    public/assets/img/**/*.svg: ['icons', 'bs:reload']
    public/**/*.php:            ['bs:reload']
    public/**/*.json:           ['bs:reload']
```

whereas now you can do 

```yaml
  default:
    public/assets/scss/**:      ['sass:site:hub:builder', 'bs:inject']
    public/assets/img/**/*.svg: ['icons', 'bs:reload']
    public/**/*.php:            ['bs:reload']
    public/**/*.json:           ['bs:reload']
```

and then provide any tasks to run in the 'before' flag

```shell
$ crossbow watch --before docker-init bs-init
```
