### ISSUE TITLE
should put trailing CLI input into ENV vars

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#73]
So that you can easily create proxy commands without users needing to set aliases on their own machine

eg commands to be run in sequence

```shell
docker-compose exec php-fpm composer install
docker-compose exec php-fpm bin/magento setup:di:compile
```

can already be aliased to something like

```shell
crossbow run setup
```

via

```yaml
tasks: 
  setup: 
    - '@sh docker-compose exec php-fpm composer install'
    - '@sh docker-compose exec php-fpm bin/magento setup:di:compile'
```

but if you wanted to add additional params (if provided) it would ideal to do something like

```yaml
tasks: 
  setup: 
    - '@sh docker-compose exec php-fpm composer install'
    - '@sh docker-compose exec php-fpm bin/magento setup:di:compile $CB_CLI_TRAILING'
```

where `$CB_CLI_TRAILING` is anything after a terminator such as `--`.

eg: 

```shell
crossbow run setup -- --myOther=args -vvv 
```

would be equivalent to running something like

```
docker-compose exec php-fpm bin/magento setup:di:compile --myOther=args -vvv
```
