### ISSUE TITLE
tasks should be able to share common options

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow-cli#83]
EG: When you want to call a task with different inputs, but 1 property is alwaya the same

before

```yaml
sass:
  tasks:
    - node-sass
  options:
    core:
      input: public/assets/scss/core.scss
      output: public/assets/css
    hub:
      input: public/assets/scss/hub.scss
      output: public/assets/css
    debug:
      input: public/assets/scss/debug.scss
      output: public/assets/css
```

notice the `output` key is repeated

**after**

```yaml
sass:
  tasks:
    - node-sass
  options:
    _shared:
      output: public/assets/css
    core:
      input: public/assets/scss/core.scss
    hub:
      input: public/assets/scss/hub.scss
    debug:
      input: public/assets/scss/debug.scss
```
